version: "3.6"

networks:
  transactions-network:
    driver: bridge

services:
  transactions:
    container_name: transactions
    build: ./
    restart: always
    volumes:
      - ./:/home/node/transactions
    working_dir: /home/node/transactions
    depends_on:
      - transactions-database
    networks:
      - transactions-network
    links:
      - transactions-database
    command: yarn dev:server

  transactions-database:
    container_name: transactions-database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: transactions
      POSTGRES_PASSWORD: transactions
    ports:
      - 5432:5432
    networks:
      - transactions-network

# docker run --name transactions-database -e POSTGRES_PASSWORD=transactions -e POSTGRES_DB=transactions -e POSTGRES_USER=transactions -p 5432:5432 -d postgres
